# syntax=docker/dockerfile:1
FROM node:20-alpine

# Tạo thư mục app
WORKDIR /app

# Copy package.json và package-lock.json
COPY package*.json ./

# Cài dependencies
RUN npm install --legacy-peer-deps

# Copy toàn bộ source
COPY . .

# Expose port React mặc định
EXPOSE 3000

# Chạy React dev server
CMD ["npm", "start"]
